"""Script to play RL agent with RSL-RL."""

import os
import sys
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Literal

import torch
import tyro

import mujoco as mj
import numpy as np
from scipy.spatial.transform import Rotation as R

from mjlab.envs import ManagerBasedRlEnv
from mjlab.rl import MjlabOnPolicyRunner, RslRlVecEnvWrapper
from mjlab.tasks.registry import list_tasks, load_env_cfg, load_rl_cfg, load_runner_cls
from mjlab.tasks.tracking.mdp import MotionCommandCfg
from mjlab.utils.os import get_wandb_checkpoint_path
from mjlab.utils.torch import configure_torch_backends
from mjlab.utils.wrappers import VideoRecorder
from mjlab.viewer import NativeMujocoViewer, ViserPlayViewer

class WireAssistWrapper:
  """Obstacle-aware cable tension controller, independent of the walking policy.

  The cable is massless and can only pull toward a fixed world-space anchor.  MuJoCo's
  ``xfrc_applied`` acts at a body's centre of mass, so the moment generated by the
  rear-back attachment point is explicitly added as ``r x F``.
  """

  (
    PHASE_APPROACH,
    PHASE_SETTLE,
    PHASE_LIFT,
    PHASE_CROSS,
    PHASE_LOWER,
    PHASE_ASSIST,
    PHASE_RELEASE,
    PHASE_DONE,
  ) = range(8)

  PHASE_NAMES = {
    PHASE_APPROACH: "APPROACH",
    PHASE_SETTLE: "SETTLE",
    PHASE_LIFT: "LIFT",
    PHASE_CROSS: "HOLD",
    PHASE_LOWER: "LOWER",
    PHASE_ASSIST: "ASSIST",
    PHASE_RELEASE: "RELEASE",
    PHASE_DONE: "DONE",
  }

  def __init__(
    self,
    env,
    traversal_mode="ascend",
    anchor_pos=(2.5, 0.0, 2.4),
    attachment_pos_b=(-0.14, 0.0, 0.40),
    obstacle_body_names=("obstacle_box", "obstacle", "wall_front"),
    lin_vel_x=1.0,
    heading_kp=0.0,
    max_yaw_rate=0.0,
    turn_in_place_threshold=np.deg2rad(8.0),
    approach_distance=0.35,
    clearance=0.10,
    lift_kp=50.0,
    lift_kd=90.0,
    pitch_kp=70.0,
    lift_support_ratio=1.25,
    max_tension=40.0 * 9.80665,
    tension_rate=1200.0,
    tension_release_rate=200.0,
    reel_in_speed=0.05,
    payout_speed=0.5,
    max_reel_in=1.00,
    hoist_target_wire_length=0.58,
    release_target_wire_length=0.90,
    winch_kp=1500.0,

    winch_kd=120.0,
    constraint_kp=500.0,
    constraint_kd=350.0,
    wire_acceleration=0.025,
    payout_acceleration=0.10,
    descent_approach_distance=0.72,
    descent_preload_reel_in=0.12, # Preload the wire by this amount before descent to reduce slack and avoid snagging.
    descent_release_wire_length=None,
    descent_landing_length_margin=0.15,
    descent_reel_in_speed=0.030,
    descent_payout_speed=0.10,
    descent_payout_acceleration=0.04,
    descent_hold_time=0.5,
    descent_posture_blend_time=2.5,
    descent_posture_action_rate_limit=0.40,
    wire_rate_filter_alpha=0.15,
    hold_length_tolerance=0.025,
    hold_rate_tolerance=0.06,
    lower_release_delay=0.0,
    lower_max_time=30.0,
    yaw_stabilization_kp=0.0,
    yaw_stabilization_kd=0.0,
    max_yaw_stabilization_torque=0.0,
    vertical_alignment_tolerance=0.08,
    wire_length_tolerance=0.02,
    lift_target_velocity=0.12,
    lift_velocity_kp=800.0,
    velocity_filter_alpha=0.20,
    pitch_soft_limit=np.deg2rad(12.0),
    pitch_hard_limit=np.deg2rad(22.0),
    pitch_payout_speed=0.45,
    lock_posture_during_lift=False,
    lift_detect_velocity=0.03,
    lift_detect_height=0.02,
    lift_detect_tension=300.0,
    wide_posture_delay=0.5,
    wide_posture_lift_height=0.02,
    brace_start_time=0.5,
    brace_blend_time=2.0,
    brace_action_rate_limit=0.80,
    wide_posture_blend_time=4.0,
    wide_posture_action_rate_limit=0.35,
    pre_lift_posture_tolerance=0.03,
    pre_lift_posture_hold_time=0.5,
    settle_wire_preload=0.01,
    settle_support_ratio=0.25,
    settle_max_tension=160.0,
    settle_wire_kp=800.0,
    settle_wire_kd=120.0,
    down_posture_blend_time=3.0,
    down_posture_action_rate_limit=0.30,
    posture_blend_time=0.5,
    landing_posture_blend_time=0.5,
    post_release_settle_time=0.5,
    policy_resume_blend_time=0.8,
    assisted_policy_hold_time=1.2,
    walk_resume_ramp_time=1.0,
    posture_action_limit=2.0,
    policy_action_filter_alpha=0.08,
    pre_lift_stand_time=1.0,
    settle_time=3.0,
    lift_min_hold_time=6.0,
    lift_max_hold_time=12.0,
    cross_hold_time=0.5,
    release_time=3.0,
    release_min_time=0.5,
    release_tension_threshold=200.0,
    log_interval=0.25,
  ):
    self.env = env
    if traversal_mode not in ("ascend", "descend"):
      raise ValueError(
        "traversal_mode must be either 'ascend' or 'descend', "
        f"got {traversal_mode!r}"
      )
    self.traversal_mode = traversal_mode
    self.anchor_pos = np.asarray(anchor_pos, dtype=np.float64)
    if self.anchor_pos.shape == (2,):
      self.anchor_pos = np.array([self.anchor_pos[0], 0.0, self.anchor_pos[1]])
    self.attachment_pos_b = np.asarray(attachment_pos_b, dtype=np.float64)
    self.lin_vel_x = lin_vel_x
    self.heading_kp = heading_kp
    self.max_yaw_rate = max_yaw_rate
    self.turn_in_place_threshold = turn_in_place_threshold
    self.approach_distance = approach_distance
    self.clearance = clearance
    self.lift_kp, self.lift_kd = lift_kp, lift_kd
    self.pitch_kp = pitch_kp
    self.lift_support_ratio = lift_support_ratio
    self.max_tension, self.tension_rate = max_tension, tension_rate
    self.tension_release_rate = tension_release_rate
    self.reel_in_speed = reel_in_speed
    self.payout_speed = payout_speed
    self.max_reel_in = max_reel_in
    self.hoist_target_wire_length = hoist_target_wire_length
    self.configured_release_target_wire_length = release_target_wire_length
    self.winch_kp = winch_kp
    self.winch_kd = winch_kd
    self.constraint_kp = constraint_kp
    self.constraint_kd = constraint_kd
    self.wire_acceleration = wire_acceleration
    self.payout_acceleration = payout_acceleration
    self.descent_approach_distance = descent_approach_distance
    self.descent_preload_reel_in = descent_preload_reel_in
    self.descent_release_wire_length = descent_release_wire_length
    self.descent_landing_length_margin = descent_landing_length_margin
    self.descent_reel_in_speed = descent_reel_in_speed
    self.descent_payout_speed = descent_payout_speed
    self.descent_payout_acceleration = descent_payout_acceleration
    self.descent_hold_time = descent_hold_time
    self.descent_posture_blend_time = descent_posture_blend_time
    self.descent_posture_action_rate_limit = (
      descent_posture_action_rate_limit
    )
    self.wire_rate_filter_alpha = wire_rate_filter_alpha
    self.hold_length_tolerance = hold_length_tolerance
    self.hold_rate_tolerance = hold_rate_tolerance
    self.lower_release_delay = lower_release_delay
    self.lower_max_time = lower_max_time
    self.yaw_stabilization_kp = yaw_stabilization_kp
    self.yaw_stabilization_kd = yaw_stabilization_kd
    self.max_yaw_stabilization_torque = max_yaw_stabilization_torque
    self.vertical_alignment_tolerance = vertical_alignment_tolerance
    self.wire_length_tolerance = wire_length_tolerance
    self.lift_target_velocity = lift_target_velocity
    self.lift_velocity_kp = lift_velocity_kp
    self.velocity_filter_alpha = velocity_filter_alpha
    self.pitch_soft_limit = pitch_soft_limit
    self.pitch_hard_limit = pitch_hard_limit
    self.pitch_payout_speed = pitch_payout_speed
    self.lock_posture_during_lift = lock_posture_during_lift
    self.lift_detect_velocity = lift_detect_velocity
    self.lift_detect_height = lift_detect_height
    self.lift_detect_tension = lift_detect_tension
    self.wide_posture_delay = wide_posture_delay
    self.wide_posture_lift_height = wide_posture_lift_height
    self.brace_start_time = brace_start_time
    self.brace_blend_time = brace_blend_time
    self.brace_action_rate_limit = brace_action_rate_limit
    self.wide_posture_blend_time = wide_posture_blend_time
    self.wide_posture_action_rate_limit = wide_posture_action_rate_limit
    self.pre_lift_posture_tolerance = pre_lift_posture_tolerance
    self.pre_lift_posture_hold_time = pre_lift_posture_hold_time
    self.settle_wire_preload = settle_wire_preload
    self.settle_support_ratio = settle_support_ratio
    self.settle_max_tension = settle_max_tension
    self.settle_wire_kp = settle_wire_kp
    self.settle_wire_kd = settle_wire_kd
    self.down_posture_blend_time = down_posture_blend_time
    self.down_posture_action_rate_limit = down_posture_action_rate_limit
    self.posture_blend_time = posture_blend_time
    self.landing_posture_blend_time = landing_posture_blend_time
    self.post_release_settle_time = post_release_settle_time
    self.policy_resume_blend_time = policy_resume_blend_time
    self.assisted_policy_hold_time = assisted_policy_hold_time
    self.walk_resume_ramp_time = walk_resume_ramp_time
    self.posture_action_limit = posture_action_limit
    self.policy_action_filter_alpha = policy_action_filter_alpha
    self.pre_lift_stand_time = pre_lift_stand_time
    self.settle_time = settle_time
    self.lift_min_hold_time = lift_min_hold_time
    self.lift_max_hold_time = lift_max_hold_time
    self.cross_hold_time = cross_hold_time
    self.release_time = release_time
    self.release_min_time = release_min_time
    self.release_tension_threshold = release_tension_threshold
    self.log_interval = log_interval
    self.dt = float(getattr(env.unwrapped, "step_dt", 0.02))

    sim = getattr(env.unwrapped, "sim", None)
    # MJLab exposes two representations: sim.mj_model is the CPU-side native
    # MjModel (names/topology), while sim.model/data are CUDA MuJoCo-Warp bridges.
    # mj_id2name only accepts the former; forces must be written to the latter.
    self.native_model = getattr(sim, "mj_model", None)
    self.mj_data = getattr(sim, "data", None)
    if self.native_model is None:
      candidate = getattr(env.unwrapped, "mj_model", None)
      if isinstance(candidate, mj.MjModel):
        self.native_model = candidate
    if self.mj_data is None:
      self.mj_data = getattr(env.unwrapped, "data", None)
    if self.native_model is None or self.mj_data is None:
      raise RuntimeError("WireAssistWrapper could not access the MuJoCo model/data")

    self.body_id = self._find_body(("torso_link", "torso", "pelvis"))
    self.obstacle_body_id = self._find_body(obstacle_body_names)
    if self.body_id < 0:
      raise ValueError("WireAssistWrapper: torso_link/pelvis body was not found")
    print(
      "[WIRE] force body: "
      f"{mj.mj_id2name(self.native_model, mj.mjtObj.mjOBJ_BODY, self.body_id)} "
      f"(id={self.body_id})",
      flush=True,
    )
    self.robot_root_id = int(self.native_model.body_rootid[self.body_id])
    if self.obstacle_body_id < 0:
      raise ValueError(
        f"WireAssistWrapper: obstacle body not found; tried {obstacle_body_names}"
      )
    self.obstacle_geom_id = self._first_box_geom(self.obstacle_body_id)
    if self.obstacle_geom_id < 0:
      raise ValueError("WireAssistWrapper: obstacle body has no box geom")
    self.anchor_visual_body_id = self._find_body(("anchor_visual",))
    self._sync_anchor_visual(sim)
    self.robot_weight = float(self.native_model.body_subtreemass[self.robot_root_id]) * 9.81
    self.robot_entity = self.env.unwrapped.scene["robot"]
    self.waist_entity_joint_ids = {}
    resolved_waist_names = {}
    for axis in ("yaw", "roll", "pitch"):
      ids, names = self.robot_entity.find_joints(f"waist_{axis}_joint")
      self.waist_entity_joint_ids[axis] = ids[0] if ids else -1
      resolved_waist_names[axis] = names[0] if names else None
    print(f"[WIRE] resolved Entity waist joints: {resolved_waist_names}", flush=True)
    if self.waist_entity_joint_ids["roll"] < 0:
      print(
        "[WIRE][WARN] waist_roll_joint is absent; observed lateral bending "
        "comes from the root/hips rather than a waist-roll joint.",
        flush=True,
      )

    self.phase = self.PHASE_APPROACH
    self.tension = 0.0
    self.nominal_attachment_z = None
    self.nominal_com_z = None
    self.previous_attachment_z = None
    self.target_heading = None
    self.heading_aligned = False
    self.phase_start_step = 0
    self.wire_length = None
    self.commanded_wire_length = None
    self.initial_wire_length = None
    self.target_wire_length = None
    self.release_target_wire_length = None
    self.settle_wire_length = None
    self.posture_lock_active = False
    self.posture_lock_step = None
    self.posture_lock_start_action = None
    self.lift_posture_action = self._build_lift_posture_action()
    self.descent_posture_action = self._build_descent_posture_action()
    self.landing_posture_action = self._build_landing_posture_action()
    self.brace_posture_action = self._build_brace_posture_action()
    self.down_posture_action = self._build_down_posture_action()
    self.waist_action_indices = []
    self.brace_action_indices = []
    self.ground_prepose_action_indices = []
    action_manager = getattr(self.env.unwrapped, "action_manager", None)
    if action_manager is not None:
      try:
        joint_term = action_manager.get_term("joint_pos")
        self.waist_action_indices = [
          index
          for index, name in enumerate(joint_term.target_names)
          if any(
            name == f"waist_{axis}_joint"
            or name.endswith(f"waist_{axis}_joint")
            for axis in ("yaw", "roll", "pitch")
          )
        ]
        self.brace_action_indices = [
          index
          for index, name in enumerate(joint_term.target_names)
          if any(
            name.endswith(suffix)
            for suffix in (
              "shoulder_pitch_joint",
              "shoulder_roll_joint",
              "elbow_joint",
            )
          )
        ]
        self.ground_prepose_action_indices = [
          index
          for index, name in enumerate(joint_term.target_names)
          if any(
            name.endswith(suffix)
            for suffix in (
              "hip_roll_joint",
              "ankle_roll_joint",
              "shoulder_pitch_joint",
              "shoulder_roll_joint",
              "elbow_joint",
            )
          )
        ]
      except (KeyError, AttributeError):
        pass
    print(
      f"[WIRE] waist action indices locked during lift-assist: "
      f"{self.waist_action_indices}",
      flush=True,
    )
    print(
      "[WIRE] policy-supported ground prepose indices: "
      f"{self.ground_prepose_action_indices}",
      flush=True,
    )
    self.filtered_lift_velocity = 0.0
    self.filtered_wire_rate = 0.0
    self.commanded_wire_rate = 0.0
    self.desired_tension = 0.0
    self.previous_yaw = None
    self.filtered_yaw_rate = 0.0
    self.heading_error = 0.0
    self.lower_command_complete_step = None
    self.filtered_policy_action = None
    self.posture_mode = None
    self.last_applied_action = None
    self.release_ready_step = None
    self.torso_roll = 0.0
    self.waist_roll_angle = 0.0
    self.waist_roll_torque = 0.0
    self.waist_angles = {axis: 0.0 for axis in ("yaw", "roll", "pitch")}
    self.waist_torques = {axis: 0.0 for axis in ("yaw", "roll", "pitch")}
    self.torso_relative_rpy = np.zeros(3, dtype=np.float64)
    self.waist_lock_active = False
    self.lift_start_attachment_z = None
    self.wide_posture_ready = False
    self.pre_lift_posture_settled_step = None
    self.pre_lift_posture_error = float("nan")
    self.brace_start_action = None
    self.brace_start_step = None
    self.step_counter = 0
    self.last_log_step = -1

  def _find_body(self, names):
    # Respect caller priority.  Scanning model order first selected pelvis
    # before torso_link because pelvis appears earlier in the body tree.
    model_names = [
      mj.mj_id2name(self.native_model, mj.mjtObj.mjOBJ_BODY, body_id)
      for body_id in range(self.native_model.nbody)
    ]
    for requested_name in names:
      requested = requested_name.lower()
      for body_id, model_name in enumerate(model_names):
        if model_name and (
          model_name.lower() == requested
          or model_name.lower().endswith(requested)
        ):
          return body_id
    for requested_name in names:
      requested = requested_name.lower()
      for body_id, model_name in enumerate(model_names):
        if model_name and requested in model_name.lower():
          return body_id
    return -1

  def _sync_anchor_visual(self, sim):
    """Move the non-physical anchor marker and visual tendon to this profile."""
    if self.anchor_visual_body_id < 0:
      print("[WIRE][WARN] anchor_visual body was not found", flush=True)
      return

    # Native MuJoCo is used by the viewer/model topology, while MJWarp performs
    # the simulation.  Update both representations in place so ascend and
    # descend modes display the same anchor used by the force controller.
    self.native_model.body_pos[self.anchor_visual_body_id] = self.anchor_pos
    mj.mj_forward(self.native_model, sim.mj_data)
    body_pos = sim.model.body_pos
    target = (
      body_pos[0, self.anchor_visual_body_id]
      if len(body_pos.shape) == 3
      else body_pos[self.anchor_visual_body_id]
    )
    target.copy_(
      torch.as_tensor(
        self.anchor_pos,
        device=target.device,
        dtype=target.dtype,
      )
    )
    sim.forward()
    print(
      f"[WIRE] visual anchor synchronized to {tuple(self.anchor_pos)}",
      flush=True,
    )

  def _find_site(self, requested_name):
    for site_id in range(self.native_model.nsite):
      name = mj.mj_id2name(self.native_model, mj.mjtObj.mjOBJ_SITE, site_id)
      if name and (name == requested_name or name.endswith(requested_name)):
        return site_id
    return -1

  def _find_joint(self, requested_name):
    for joint_id in range(self.native_model.njnt):
      name = mj.mj_id2name(self.native_model, mj.mjtObj.mjOBJ_JOINT, joint_id)
      if name and (name == requested_name or name.endswith(requested_name)):
        return joint_id
    return -1

  def _build_lift_posture_action(self):
    """Wide posture: high yaw inertia and a broad front contact envelope."""
    return self._build_posture_action(
      {
        "left_hip_pitch_joint": -0.0,
        "right_hip_pitch_joint": -0.0,
        "left_hip_roll_joint": 0.40,
        "right_hip_roll_joint": -0.40,
        "left_knee_joint": 0.55,
        "right_knee_joint": 0.55,
        "left_ankle_pitch_joint": -0.35,
        "right_ankle_pitch_joint": -0.35,
        "left_ankle_roll_joint": -0.26,
        "right_ankle_roll_joint": 0.26,
        "waist_yaw_joint": 0.0,
        "waist_roll_joint": 0.0,
        "waist_pitch_joint": 0.0,
        "left_shoulder_pitch_joint": 0.50,
        "right_shoulder_pitch_joint": 0.50,
        "left_shoulder_roll_joint": 1.50,
        "right_shoulder_roll_joint": -1.50,
        "left_elbow_joint": 0.35,
        "right_elbow_joint": 0.35,
      }
    )

  def _build_descent_posture_action(self):
    """Feet-down suspension posture for a controlled step descent.

    The legs remain mildly abducted for lateral stability, while hip/knee/ankle
    flexion keeps both soles below the pelvis and ready to accept ground load.
    The arms increase yaw inertia without becoming the primary contact point.
    """
    return self._build_posture_action(
      {
        "left_hip_pitch_joint": -0.12,
        "right_hip_pitch_joint": -0.12,
        "left_hip_roll_joint": 0.26,
        "right_hip_roll_joint": -0.26,
        "left_knee_joint": 0.45,
        "right_knee_joint": 0.45,
        "left_ankle_pitch_joint": -0.28,
        "right_ankle_pitch_joint": -0.28,
        "left_ankle_roll_joint": -0.16,
        "right_ankle_roll_joint": 0.16,
        "waist_yaw_joint": 0.0,
        "waist_roll_joint": 0.0,
        "waist_pitch_joint": 0.0,
        "left_shoulder_pitch_joint": 0.35,
        "right_shoulder_pitch_joint": 0.35,
        "left_shoulder_roll_joint": 1.10,
        "right_shoulder_roll_joint": -1.10,
        "left_elbow_joint": 0.50,
        "right_elbow_joint": 0.50,
      }
    )

  def _build_landing_posture_action(self):
    """Feet-down, slightly crouched posture held through touchdown."""
    return self._build_posture_action(
      {
        "left_hip_pitch_joint": -0.25,
        "right_hip_pitch_joint": -0.25,
        "left_hip_roll_joint": 0.08,
        "right_hip_roll_joint": -0.08,
        "left_knee_joint": 0.55,
        "right_knee_joint": 0.55,
        "left_ankle_pitch_joint": -0.30,
        "right_ankle_pitch_joint": -0.30,
        "left_ankle_roll_joint": 0.0,
        "right_ankle_roll_joint": 0.0,
        "waist_yaw_joint": 0.0,
        "waist_roll_joint": 0.0,
        "waist_pitch_joint": 0.0,
        "left_shoulder_pitch_joint": 0.0,
        "right_shoulder_pitch_joint": 0.0,
        "left_shoulder_roll_joint": 0.25,
        "right_shoulder_roll_joint": -0.25,
        "left_elbow_joint": 0.55,
        "right_elbow_joint": 0.55,
      }
    )

  def _build_brace_posture_action(self):
    """Put both arms diagonally forward before hoisting starts."""
    return self._build_posture_action(
      {
        "left_shoulder_pitch_joint": -0.50,
        "right_shoulder_pitch_joint": -0.50,
        "left_shoulder_roll_joint": 0.70,
        "right_shoulder_roll_joint": -0.70,
        "left_elbow_joint": 0.25,
        "right_elbow_joint": 0.25,
      }
    )

  def _build_down_posture_action(self):
    """Keep the wide stance but move both soles forward of the COM."""
    return self._build_posture_action(
      {
        "left_hip_pitch_joint": -0.40,
        "right_hip_pitch_joint": -0.40,
        "left_hip_roll_joint": 0.40,
        "right_hip_roll_joint": -0.40,
        "left_knee_joint": 0.75,
        "right_knee_joint": 0.75,
        "left_ankle_pitch_joint": -0.40,
        "right_ankle_pitch_joint": -0.40,
        "left_ankle_roll_joint": -0.26,
        "right_ankle_roll_joint": 0.26,
        "waist_yaw_joint": 0.0,
        "waist_roll_joint": 0.0,
        "waist_pitch_joint": 0.12,
        "left_shoulder_pitch_joint": 0.50,
        "right_shoulder_pitch_joint": 0.50,
        "left_shoulder_roll_joint": 1.50,
        "right_shoulder_roll_joint": -1.50,
        "left_elbow_joint": 0.35,
        "right_elbow_joint": 0.35,
      }
    )

  def _build_posture_action(self, desired):
    action_manager = getattr(self.env.unwrapped, "action_manager", None)
    if action_manager is None:
      return None
    try:
      term = action_manager.get_term("joint_pos")
      names, offset, scale = term.target_names, term.offset, term.scale
    except (KeyError, AttributeError):
      return None

    posture = torch.zeros_like(term.raw_action)
    for index, name in enumerate(names):
      requested_name = next(
        (
          candidate
          for candidate in desired
          if name == candidate or name.endswith(candidate)
        ),
        None,
      )
      if requested_name is None:
        continue
      joint_offset = offset[:, index] if hasattr(offset, "ndim") else offset
      joint_scale = scale[:, index] if hasattr(scale, "ndim") else scale
      posture[:, index] = (desired[requested_name] - joint_offset) / joint_scale
    return torch.clamp(
      posture, -self.posture_action_limit, self.posture_action_limit
    )

  def _rate_limit_action(self, target, previous, rate_limit, indices=None):
    """Limit normalized joint-action motion to ``rate_limit`` per second."""
    if previous is None or rate_limit is None or rate_limit <= 0.0:
      return target
    previous = previous.to(device=target.device, dtype=target.dtype)
    max_delta = float(rate_limit) * self.dt
    if indices is None:
      return previous + torch.clamp(target - previous, -max_delta, max_delta)
    limited = target.clone()
    limited[:, indices] = previous[:, indices] + torch.clamp(
      target[:, indices] - previous[:, indices], -max_delta, max_delta
    )
    return limited

  def _first_box_geom(self, body_id):
    for geom_id in range(self.native_model.ngeom):
      if (
        self.native_model.geom_bodyid[geom_id] == body_id
        and self.native_model.geom_type[geom_id] == mj.mjtGeom.mjGEOM_BOX
      ):
        return geom_id
    return -1

  @staticmethod
  def _numpy(value):
    return value.detach().cpu().numpy() if hasattr(value, "detach") else np.asarray(value)

  def _env0(self, value, item_id):
    array = self._numpy(value)
    return np.array(array[0, item_id] if array.ndim == 3 else array[item_id], copy=True)

  def _scalar_env0(self, value, item_id):
    array = self._numpy(value)
    return float(array[0, item_id] if array.ndim == 2 else array[item_id])

  @staticmethod
  def _wrap_to_pi(angle):
    return (angle + np.pi) % (2.0 * np.pi) - np.pi

  def _set_walking_command(self, yaw=None, allow_forward=True, forward_scale=1.0):
    """Command forward motion only; active yaw control is disabled."""
    command_manager = getattr(self.env.unwrapped, "command_manager", None)
    if command_manager is None:
      return False
    try:
      command = command_manager.get_command("twist")
      self.heading_aligned = True
      self.heading_error = 0.0
      target = torch.tensor(
        [
          self.lin_vel_x * float(np.clip(forward_scale, 0.0, 1.0))
          if allow_forward
          else 0.0,
          0.0,
          0.0,
        ],
        device=command.device,
        dtype=command.dtype,
      )
      with torch.no_grad():
        command[:] = target
    except (KeyError, AttributeError):
      return False
    return True

  def _obstacle_bounds(self):
    geom_xpos = getattr(self.mj_data, "geom_xpos", None)
    center = (
      self._env0(geom_xpos, self.obstacle_geom_id)
      if geom_xpos is not None
      else self._env0(self.mj_data.xpos, self.obstacle_body_id)
    )
    half_size = np.asarray(self.native_model.geom_size[self.obstacle_geom_id])
    # The research setup assumes an axis-aligned rectangular obstacle in x-z.
    return (
      center[0] - half_size[0],
      center[0] + half_size[0],
      center[2] - half_size[2],
      center[2] + half_size[2],
    )

  def _robot_state(self):
    torso_pos = self._env0(self.mj_data.xpos, self.body_id)
    quat_wxyz = self._env0(self.mj_data.xquat, self.body_id)
    rotation = R.from_quat(
      [quat_wxyz[1], quat_wxyz[2], quat_wxyz[3], quat_wxyz[0]]
    )
    attachment_pos = torso_pos + rotation.apply(self.attachment_pos_b)
    robot_com = self._env0(self.mj_data.subtree_com, self.robot_root_id)
    body_com = self._env0(self.mj_data.xipos, self.body_id)
    torso_euler = rotation.as_euler("xyz", degrees=False)
    self.torso_roll = float(torso_euler[0])
    pitch = torso_euler[1]
    root_quat_wxyz = self._env0(self.mj_data.xquat, self.robot_root_id)
    root_rotation = R.from_quat(
      [root_quat_wxyz[1], root_quat_wxyz[2], root_quat_wxyz[3], root_quat_wxyz[0]]
    )
    self.torso_relative_rpy = (
      root_rotation.inv() * rotation
    ).as_euler("xyz", degrees=False)
    yaw = root_rotation.as_euler("xyz", degrees=False)[2]
    if self.previous_yaw is not None:
      yaw_rate = self._wrap_to_pi(yaw - self.previous_yaw) / self.dt
      self.filtered_yaw_rate += 0.2 * (yaw_rate - self.filtered_yaw_rate)
    self.previous_yaw = yaw
    vz = 0.0
    if self.previous_attachment_z is not None:
      vz = (attachment_pos[2] - self.previous_attachment_z) / self.dt
    self.previous_attachment_z = attachment_pos[2]
    self.filtered_lift_velocity += self.velocity_filter_alpha * (
      vz - self.filtered_lift_velocity
    )
    vz = self.filtered_lift_velocity
    return robot_com, body_com, attachment_pos, rotation, pitch, yaw, vz

  def _set_phase(self, phase):
    if phase != self.phase:
      old_phase = self.PHASE_NAMES[self.phase]
      self.phase = phase
      self.phase_start_step = self.step_counter
      print(
        f"[WIRE] phase {old_phase} -> {self.PHASE_NAMES[phase]} "
        f"(t={self.step_counter * self.dt:.2f}s)",
        flush=True,
      )

  def _phase_time(self):
    return (self.step_counter - self.phase_start_step) * self.dt

  def _legacy_desired_tension_unused(
    self, robot_com, body_com, attachment_pos, pitch, vz
  ):
    """Deprecated controller retained temporarily for parameter comparison only."""
    box_front, box_back, box_bottom, box_top = self._obstacle_bounds()
    x = attachment_pos[0]
    if self.nominal_attachment_z is None:
      self.nominal_attachment_z = attachment_pos[2]
    if self.nominal_com_z is None:
      self.nominal_com_z = robot_com[2]
    target_z = self.nominal_attachment_z + (box_top - box_bottom) + self.clearance

    if self.phase == self.PHASE_APPROACH and x >= box_front - self.approach_distance:
      self._set_phase(self.PHASE_SETTLE)
    pre_lift_time = max(
      self.settle_time,
      self.brace_start_time + self.brace_blend_time,
    )
    if self.phase == self.PHASE_SETTLE and self._phase_time() >= pre_lift_time:
      self._set_phase(self.PHASE_LIFT)
    if self.phase == self.PHASE_LIFT:
      lifted_over_box = attachment_pos[2] >= target_z and x >= box_front
      if (lifted_over_box and self._phase_time() >= self.lift_min_hold_time) or (
        self._phase_time() >= self.lift_max_hold_time
      ):
        self._set_phase(self.PHASE_CROSS)
    if self.phase == self.PHASE_CROSS and self._phase_time() >= self.cross_hold_time:
      self._set_phase(self.PHASE_LOWER)
    if self.phase == self.PHASE_LOWER and self._phase_time() >= self.release_time:
      self._set_phase(self.PHASE_DONE)

    cable = self.anchor_pos - attachment_pos
    actual_length = float(np.linalg.norm(cable))
    if actual_length < 1e-6:
      return 0.0

    if self.wire_length is None:
      self.wire_length = actual_length
      self.commanded_wire_length = actual_length
      self.initial_wire_length = actual_length

    previous_actual_length = self.wire_length
    previous_commanded_length = self.commanded_wire_length
    self.wire_length = actual_length

    if self.phase == self.PHASE_APPROACH:
      # Before the obstacle the winch pays out freely, so the cable stays slack.
      self.commanded_wire_length = actual_length
      self.initial_wire_length = actual_length
    elif self.phase in (self.PHASE_LIFT, self.PHASE_CROSS):
      minimum_length = self.initial_wire_length - self.max_reel_in
      self.commanded_wire_length = max(
        minimum_length,
        self.commanded_wire_length - self.reel_in_speed * self.dt,
      )
    elif self.phase == self.PHASE_LOWER:
      self.commanded_wire_length = min(
        self.initial_wire_length,
        self.commanded_wire_length + self.payout_speed * self.dt,
      )
    elif self.phase == self.PHASE_DONE:
      self.commanded_wire_length = actual_length

    # The rear attachment creates a forward pitching moment.  If the torso
    # starts pitching forward, stop reel-in and pay cable out instead.
    if pitch > self.pitch_soft_limit and self.phase in (
      self.PHASE_LIFT,
      self.PHASE_CROSS,
    ):
      self.commanded_wire_length = min(
        self.initial_wire_length,
        max(self.commanded_wire_length, previous_commanded_length)
        + self.pitch_payout_speed * self.dt,
      )

    actual_length_rate = (actual_length - previous_actual_length) / self.dt
    commanded_length_rate = (
      self.commanded_wire_length - previous_commanded_length
    ) / self.dt
    extension = max(0.0, actual_length - self.commanded_wire_length)
    extension_rate = actual_length_rate - commanded_length_rate
    target_tension = self.winch_kp * extension + self.winch_kd * extension_rate

    # Length control alone can go slack as the robot follows the cable.  During
    # lifting, add the exact cable tension needed to balance gravity, then close
    # the loop on vertical velocity so the body rises at a controlled speed.
    if self.phase == self.PHASE_LIFT:
      vertical_direction = max(cable[2] / actual_length, 0.10)
      hover_tension = self.robot_weight / vertical_direction
      velocity_tension = self.lift_velocity_kp * (self.lift_target_velocity - vz)
      target_tension = max(target_tension, hover_tension + velocity_tension)
    pitch_scale = np.clip(
      (self.pitch_hard_limit - pitch)
      / (self.pitch_hard_limit - self.pitch_soft_limit),
      0.0,
      1.0,
    )
    target_tension *= pitch_scale

    # The cable cannot push; SETTLE intentionally leaves it slack before reel-in.
    if self.phase in (self.PHASE_APPROACH, self.PHASE_SETTLE, self.PHASE_DONE):
      return 0.0
    return float(np.clip(target_tension, 0.0, self.max_tension))

  def _apply_cable_force(self, body_com, attachment_pos, desired_tension):
    limited_target = float(np.clip(desired_tension, 0.0, self.max_tension))
    # Active hoisting/lowering needs enough bandwidth to brake oscillation.
    # Only the final RELEASE uses the deliberately gentle force ramp-down.
    rate_limit = (
      self.tension_release_rate
      if self.phase == self.PHASE_RELEASE and limited_target < self.tension
      else self.tension_rate
    )
    max_delta = rate_limit * self.dt
    self.tension += float(
      np.clip(limited_target - self.tension, -max_delta, max_delta)
    )
    self.desired_tension = limited_target
    cable = self.anchor_pos - attachment_pos
    cable_length = np.linalg.norm(cable)
    force = np.zeros(3) if cable_length < 1e-6 else self.tension * cable / cable_length
    # Apply only the moment generated by the real rear attachment point.
    torque = np.cross(attachment_pos - body_com, force)
    wrench = np.concatenate((force, torque)).astype(np.float32)

    xfrc = self.mj_data.xfrc_applied
    target = xfrc[0, self.body_id] if len(xfrc.shape) == 3 else xfrc[self.body_id]
    if hasattr(target, "copy_"):
      target.copy_(torch.as_tensor(wrench, device=target.device, dtype=target.dtype))
    else:
      target[:] = wrench

  def _update_waist_diagnostics(self):
    """Read waist state through Entity indexing; never write qfrc_applied."""
    joint_pos = self.robot_entity.data.joint_pos
    for axis in ("yaw", "roll", "pitch"):
      joint_id = self.waist_entity_joint_ids.get(axis, -1)
      if joint_id < 0:
        self.waist_angles[axis] = 0.0
        self.waist_torques[axis] = 0.0
        continue
      self.waist_angles[axis] = float(joint_pos[0, joint_id].item())
      self.waist_torques[axis] = 0.0

    self.waist_roll_angle = self.waist_angles["roll"]
    self.waist_roll_torque = 0.0

  def _configure_descent_wire_targets(
    self,
    attachment_pos,
    actual_length,
    box_bottom,
    box_top,
    announce=False,
  ):
    """Update preload and landing lengths from the current support posture."""
    self.target_wire_length = max(
      actual_length - self.descent_preload_reel_in,
      0.05,
    )
    attachment_height_above_support = max(
      attachment_pos[2] - box_top,
      0.0,
    )
    ground_attachment_z = box_bottom + attachment_height_above_support
    computed_landing_length = (
      self.anchor_pos[2]
      - ground_attachment_z
      + self.descent_landing_length_margin
    )
    requested_landing_length = (
      computed_landing_length
      if self.descent_release_wire_length is None
      else float(self.descent_release_wire_length)
    )
    self.release_target_wire_length = max(
      requested_landing_length,
      self.target_wire_length,
    )
    if announce:
      print(
        "[WIRE] descent profile armed: "
        f"Lpreload={self.target_wire_length:.3f}m "
        f"Llanding={self.release_target_wire_length:.3f}m",
        flush=True,
      )

  def _inextensible_cable_tension(self, attachment_pos):
    """Reel an inextensible cable at constant speed to a fixed hoist length."""
    box_front, box_back, box_bottom, box_top = self._obstacle_bounds()
    cable = self.anchor_pos - attachment_pos
    actual_length = float(np.linalg.norm(cable))
    if actual_length < 1e-6:
      return 0.0

    if self.wire_length is None:
      self.wire_length = actual_length
      self.commanded_wire_length = actual_length
      self.initial_wire_length = actual_length
    previous_actual = self.wire_length
    previous_commanded = self.commanded_wire_length
    self.wire_length = actual_length

    if self.phase == self.PHASE_APPROACH:
      self.commanded_wire_length = actual_length
      self.initial_wire_length = actual_length
      approach_edge = (
        box_back if self.traversal_mode == "descend" else box_front
      )
      approach_distance = (
        self.descent_approach_distance
        if self.traversal_mode == "descend"
        else self.approach_distance
      )
      if attachment_pos[0] >= approach_edge - approach_distance:
        if self.traversal_mode == "descend":
          # Preload the cable without hoisting the robot high above the top
          # surface.  The forward-offset anchor then transfers the suspended
          # body beyond the edge before controlled payout begins.
          self._configure_descent_wire_targets(
            attachment_pos,
            self.initial_wire_length,
            box_bottom,
            box_top,
            announce=True,
          )
        else:
          self.target_wire_length = max(
            min(self.hoist_target_wire_length, self.initial_wire_length),
            0.05,
          )
          self.release_target_wire_length = (
            self.initial_wire_length
            if self.configured_release_target_wire_length is None
            else max(
              float(self.configured_release_target_wire_length),
              self.target_wire_length,
            )
          )
        self.settle_wire_length = max(
          actual_length - self.settle_wire_preload,
          0.05,
        )
        print(
          "[WIRE] SETTLE cable length latched: "
          f"Lsettle={self.settle_wire_length:.3f}m",
          flush=True,
        )
        self._set_phase(self.PHASE_SETTLE)

    if self.phase == self.PHASE_SETTLE:
      # Hold the entry length instead of following the measured length.  A
      # capped support tension then restrains torso translation while the
      # standing policy performs the ground pre-pose transition.
      if self.settle_wire_length is None:
        self.settle_wire_length = max(
          actual_length - self.settle_wire_preload,
          0.05,
        )
      self.commanded_wire_length = self.settle_wire_length
      self.initial_wire_length = actual_length
      if (
        self.traversal_mode == "ascend"
        and self.configured_release_target_wire_length is None
      ):
        self.release_target_wire_length = actual_length

    posture_hold_complete = (
      self.pre_lift_posture_settled_step is not None
      and (
        self.step_counter - self.pre_lift_posture_settled_step
      )
      * self.dt
      >= self.pre_lift_posture_hold_time
    )
    if self.phase == self.PHASE_SETTLE and posture_hold_complete:
      # Recompute the LIFT target only after the on-ground posture transition.
      self.initial_wire_length = actual_length
      if self.traversal_mode == "descend":
        self._configure_descent_wire_targets(
          attachment_pos,
          actual_length,
          box_bottom,
          box_top,
          announce=True,
        )
      else:
        self.target_wire_length = max(
          min(self.hoist_target_wire_length, actual_length),
          0.05,
        )
      self._set_phase(self.PHASE_LIFT)

    if self.phase == self.PHASE_LIFT:
      # Decelerate the winch command before the target.  A cable cannot push the
      # robot back down after an overshoot, so arriving with near-zero radial
      # velocity is essential.
      remaining = max(self.commanded_wire_length - self.target_wire_length, 0.0)
      reel_speed = min(
        self.descent_reel_in_speed
        if self.traversal_mode == "descend"
        else self.reel_in_speed,
        np.sqrt(2.0 * self.wire_acceleration * remaining),
      )
      self.commanded_wire_length = max(
        self.target_wire_length,
        self.commanded_wire_length - reel_speed * self.dt,
      )

    hold_time = (
      self.descent_hold_time
      if self.traversal_mode == "descend"
      else self.cross_hold_time
    )
    if self.phase == self.PHASE_CROSS and self._phase_time() >= hold_time:
      self._set_phase(self.PHASE_LOWER)
    if self.phase == self.PHASE_LOWER:
      # Keep the cable taut while paying it out.  The same length constraint
      # used for hoisting therefore brakes the descent instead of dropping the
      # robot under gravity.
      release_length = self.release_target_wire_length or self.initial_wire_length
      remaining = max(release_length - self.commanded_wire_length, 0.0)
      payout_speed = min(
        self.descent_payout_speed
        if self.traversal_mode == "descend"
        else self.payout_speed,
        np.sqrt(
          2.0
          * (
            self.descent_payout_acceleration
            if self.traversal_mode == "descend"
            else self.payout_acceleration
          )
          * remaining
        ),
      )
      self.commanded_wire_length = min(
        release_length,
        self.commanded_wire_length + payout_speed * self.dt,
      )
      command_finished = self.commanded_wire_length >= release_length - 1e-6
      if command_finished and self.lower_command_complete_step is None:
        self.lower_command_complete_step = self.step_counter
    if self.phase == self.PHASE_RELEASE:
      # Once the slow payout is complete, ramp the tension down through the
      # common tension-rate limiter.  DONE is selected after force application.
      self.commanded_wire_length = (
        self.release_target_wire_length or self.initial_wire_length
      )
    if self.phase == self.PHASE_ASSIST:
      # Keep the cable at the landing length while the standing policy is
      # blended back in.  The cable continues supporting the robot here.
      self.commanded_wire_length = (
        self.release_target_wire_length or self.initial_wire_length
      )
      if self._phase_time() >= max(
        self.assisted_policy_hold_time,
        self.policy_resume_blend_time,
      ):
        self._set_phase(self.PHASE_RELEASE)
    if self.phase == self.PHASE_DONE:
      self.commanded_wire_length = actual_length

    actual_rate = (actual_length - previous_actual) / self.dt
    commanded_rate = (self.commanded_wire_length - previous_commanded) / self.dt
    self.filtered_wire_rate += self.wire_rate_filter_alpha * (
      actual_rate - self.filtered_wire_rate
    )
    self.commanded_wire_rate = commanded_rate
    length_error = actual_length - self.commanded_wire_length
    rate_error = self.filtered_wire_rate - commanded_rate
    vertical_fraction = max(cable[2] / actual_length, 0.05)
    if self.phase == self.PHASE_SETTLE:
      support_tension = (
        self.settle_support_ratio * self.robot_weight / vertical_fraction
      )
      settle_tension = (
        support_tension
        + self.settle_wire_kp * length_error
        + self.settle_wire_kd * rate_error
      )
      return float(
        np.clip(settle_tension, 0.0, self.settle_max_tension)
      )
    tension = (
      self.robot_weight / vertical_fraction
      + self.constraint_kp * length_error
      + self.constraint_kd * rate_error
    )

    # Do not start the hold timer while the body is still flying through the
    # target.  Both cable length and radial speed must have settled.
    if self.phase == self.PHASE_LIFT:
      length_settled = abs(length_error) <= self.hold_length_tolerance
      rate_settled = abs(self.filtered_wire_rate) <= self.hold_rate_tolerance
      command_finished = self.commanded_wire_length <= self.target_wire_length + 1e-6
      if command_finished and length_settled and rate_settled:
        self._set_phase(self.PHASE_CROSS)
    elif self.phase == self.PHASE_LOWER:
      release_delay_elapsed = (
        self.lower_command_complete_step is not None
        and (self.step_counter - self.lower_command_complete_step) * self.dt
        >= self.lower_release_delay
      )
      if release_delay_elapsed:
        self._set_phase(self.PHASE_ASSIST)
    if self.phase in (
      self.PHASE_APPROACH,
      self.PHASE_RELEASE,
      self.PHASE_DONE,
    ):
      return 0.0
    return max(float(tension), 0.0)

  def _log_wire_state(self, attachment_pos, vz):
    interval_steps = max(1, int(round(self.log_interval / self.dt)))
    if self.last_log_step >= 0 and self.step_counter - self.last_log_step < interval_steps:
      return
    self.last_log_step = self.step_counter
    commanded = self.commanded_wire_length
    target = self.target_wire_length
    print(
      f"[WIRE] t={self.step_counter * self.dt:7.2f}s "
      f"phase={self.PHASE_NAMES[self.phase]:8s} "
      f"L={self.wire_length if self.wire_length is not None else float('nan'):.3f}m "
      f"Lcmd={commanded if commanded is not None else float('nan'):.3f}m "
      f"Ltarget={target if target is not None else float('nan'):.3f}m "
      f"Lrelease={self.release_target_wire_length if self.release_target_wire_length is not None else float('nan'):.3f}m "
      f"Lsettle={self.settle_wire_length if self.settle_wire_length is not None else float('nan'):.3f}m "
      f"Ldot={self.filtered_wire_rate:+.3f}m/s "
      f"Ldot_cmd={self.commanded_wire_rate:+.3f}m/s "
      f"T={self.tension:6.1f}/{self.desired_tension:6.1f}N "
      f"yaw_err={np.rad2deg(self.heading_error):+.1f}deg "
      f"yaw_rate={np.rad2deg(self.filtered_yaw_rate):+.1f}deg/s "
      f"roll={np.rad2deg(self.torso_roll):+.1f}deg "
      f"waist_ypr=({np.rad2deg(self.waist_angles['yaw']):+.1f},"
      f"{np.rad2deg(self.waist_angles['pitch']):+.1f},"
      f"{np.rad2deg(self.waist_angles['roll']):+.1f})deg "
      f"waist_extra_tau=({self.waist_torques['yaw']:+.1f},"
      f"{self.waist_torques['pitch']:+.1f},"
      f"{self.waist_torques['roll']:+.1f})Nm "
      f"waist_lock={'ON' if self.waist_lock_active else 'OFF'} "
      f"posture={self.posture_mode or 'policy'} "
      f"prepose_err={self.pre_lift_posture_error:.3f} "
      f"lift_dz={attachment_pos[2] - self.lift_start_attachment_z if self.lift_start_attachment_z is not None else 0.0:+.3f}m "
      f"wide={'ON' if self.wide_posture_ready else 'OFF'} "
      f"torso_rel_rpy=({np.rad2deg(self.torso_relative_rpy[0]):+.1f},"
      f"{np.rad2deg(self.torso_relative_rpy[1]):+.1f},"
      f"{np.rad2deg(self.torso_relative_rpy[2]):+.1f})deg "
      f"z_back={attachment_pos[2]:.3f}m "
      f"vz={vz:+.3f}m/s",
      flush=True,
    )

  def _reset_controller_state(self):
    """Reset only wrapper state after MJLab has reset the simulation itself."""
    self.phase = self.PHASE_APPROACH
    self.tension = 0.0
    self.nominal_attachment_z = None
    self.nominal_com_z = None
    self.previous_attachment_z = None
    self.heading_aligned = False
    self.phase_start_step = 0
    self.step_counter = 0
    self.target_heading = None
    self.wire_length = None
    self.commanded_wire_length = None
    self.initial_wire_length = None
    self.target_wire_length = None
    self.release_target_wire_length = None
    self.settle_wire_length = None
    self.posture_lock_active = False
    self.posture_lock_step = None
    self.posture_lock_start_action = None
    self.filtered_lift_velocity = 0.0
    self.filtered_wire_rate = 0.0
    self.commanded_wire_rate = 0.0
    self.desired_tension = 0.0
    self.previous_yaw = None
    self.filtered_yaw_rate = 0.0
    self.heading_error = 0.0
    self.lower_command_complete_step = None
    self.filtered_policy_action = None
    self.posture_mode = None
    self.last_applied_action = None
    self.release_ready_step = None
    self.torso_roll = 0.0
    self.waist_roll_angle = 0.0
    self.waist_roll_torque = 0.0
    self.waist_angles = {axis: 0.0 for axis in ("yaw", "roll", "pitch")}
    self.waist_torques = {axis: 0.0 for axis in ("yaw", "roll", "pitch")}
    self.torso_relative_rpy = np.zeros(3, dtype=np.float64)
    self.waist_lock_active = False
    self.lift_start_attachment_z = None
    self.wide_posture_ready = False
    self.pre_lift_posture_settled_step = None
    self.pre_lift_posture_error = float("nan")
    self.brace_start_action = None
    self.last_log_step = -1

    # At this point MJLab has already called sim.forward(), so all poses describe
    # the new episode and can safely initialize the rule-based controller.
    robot_com, _, _, _, _, yaw, _ = self._robot_state()
    direction = self.anchor_pos - robot_com
    self.target_heading = float(np.arctan2(direction[1], direction[0]))
    self._set_walking_command(yaw, allow_forward=True)

  @staticmethod
  def _has_finished_episode(value):
    if value is None:
      return False
    if hasattr(value, "any"):
      result = value.any()
      return bool(result.item() if hasattr(result, "item") else result)
    return bool(np.any(value))

  def step(self, action):
    self.step_counter += 1
    robot_com, body_com, attachment_pos, _, pitch, yaw, vz = self._robot_state()
    if self.target_heading is None:
      direction = self.anchor_pos - robot_com
      self.target_heading = float(np.arctan2(direction[1], direction[0]))
    heading_aligned = self._set_walking_command(yaw, allow_forward=False)
    desired = self._inextensible_cable_tension(attachment_pos) if heading_aligned else 0.0
    self._apply_cable_force(body_com, attachment_pos, desired)
    if self.phase == self.PHASE_LIFT:
      if self.lift_start_attachment_z is None:
        self.lift_start_attachment_z = float(attachment_pos[2])
      lifted_height = attachment_pos[2] - self.lift_start_attachment_z
      posture_ready = lifted_height >= self.wide_posture_lift_height
      if self.traversal_mode == "descend":
        posture_ready = (
          lifted_height >= 0.01
          or self.tension >= 0.70 * self.robot_weight
          or self._phase_time() >= self.wide_posture_delay + 0.5
        )
      if (
        not self.wide_posture_ready
        and self._phase_time() >= self.wide_posture_delay
        and posture_ready
      ):
        self.wide_posture_ready = True
        print(
          f"[WIRE] support established (dz={lifted_height:+.3f}m); "
          f"locking {self.traversal_mode} posture",
          flush=True,
        )
    waist_control_enabled = (
      self.phase in (
        self.PHASE_LIFT,
        self.PHASE_CROSS,
        self.PHASE_LOWER,
        self.PHASE_ASSIST,
      )
    )
    self.waist_lock_active = waist_control_enabled
    self._update_waist_diagnostics()
    release_ready = (
      self.phase == self.PHASE_RELEASE
      and self._phase_time() >= self.release_min_time
      and self.tension <= self.release_tension_threshold
    )
    if release_ready and self.release_ready_step is None:
      self.release_ready_step = self.step_counter
      print("[WIRE] release tension threshold reached", flush=True)
    if (
      self.phase == self.PHASE_RELEASE
      and self.release_ready_step is not None
      and (self.step_counter - self.release_ready_step) * self.dt
      >= self.post_release_settle_time
    ):
      self._set_phase(self.PHASE_DONE)
    self._log_wire_state(attachment_pos, vz)
    allow_forward = self.phase in (self.PHASE_APPROACH, self.PHASE_DONE)
    forward_scale = (
      min(self._phase_time() / self.walk_resume_ramp_time, 1.0)
      if self.phase == self.PHASE_DONE
      else 1.0
    )
    self._set_walking_command(
      yaw,
      allow_forward=allow_forward,
      forward_scale=forward_scale,
    )

    desired_posture_mode = None
    target_posture = None
    transition_time = self.posture_blend_time
    action_rate_limit = None
    if self.phase == self.PHASE_SETTLE:
      # Keep the standing policy active for the sagittal support joints.  Only
      # yaw-sensitive lateral stance joints and the arms approach the fixed
      # suspension pose while both feet remain on the support surface.
      desired_posture_mode = f"{self.traversal_mode}_ground_prepose"
      if self.traversal_mode == "descend":
        target_posture = self.descent_posture_action
        transition_time = self.descent_posture_blend_time
        action_rate_limit = self.descent_posture_action_rate_limit
      else:
        target_posture = self.lift_posture_action
        transition_time = self.wide_posture_blend_time
        action_rate_limit = self.wide_posture_action_rate_limit
    elif self.phase in (
      self.PHASE_LIFT,
      self.PHASE_CROSS,
      self.PHASE_LOWER,
    ):
      if self.traversal_mode == "descend":
        desired_posture_mode = "descent_feet_down"
        target_posture = self.descent_posture_action
        transition_time = self.descent_posture_blend_time
        action_rate_limit = self.descent_posture_action_rate_limit
      else:
        desired_posture_mode = "wide_lift"
        target_posture = self.lift_posture_action
        transition_time = self.wide_posture_blend_time
        action_rate_limit = self.wide_posture_action_rate_limit

    if desired_posture_mode is not None and desired_posture_mode != self.posture_mode:
      self.posture_mode = desired_posture_mode
      self.posture_lock_active = True
      self.posture_lock_step = self.step_counter
      self.posture_lock_start_action = (
        self.last_applied_action.detach().clone()
        if self.last_applied_action is not None
        else action.detach().clone()
      )
      print(f"[WIRE] posture locked: {desired_posture_mode}", flush=True)

    if (
      desired_posture_mode is not None
      and self.posture_lock_start_action is not None
      and self.posture_lock_step is not None
    ):
      blend = np.clip(
        (self.step_counter - self.posture_lock_step) * self.dt
        / transition_time,
        0.0,
        1.0,
      )
      target_action = (
        target_posture.to(device=action.device, dtype=action.dtype)
        if target_posture is not None
        else torch.zeros_like(action)
      )
      if self.phase == self.PHASE_SETTLE:
        # ``action`` is the current standing-policy output.  Preserve it for
        # hip/knee/ankle pitch and all other balance joints; interpolate only
        # the selected lateral stance and arm joints.
        indices = self.ground_prepose_action_indices
        policy_supported_action = action.clone()
        policy_supported_action[:, indices] = (
          (1.0 - blend) * self.posture_lock_start_action[:, indices]
          + blend * target_action[:, indices]
        )
        action = self._rate_limit_action(
          policy_supported_action,
          self.last_applied_action,
          action_rate_limit,
          indices=indices,
        )
        posture_error = float(
          torch.max(
            torch.abs(action[:, indices] - target_action[:, indices])
          ).item()
        )
        self.pre_lift_posture_error = posture_error
        posture_settled = (
          self._phase_time() >= self.settle_time
          and posture_error <= self.pre_lift_posture_tolerance
        )
        if posture_settled and self.pre_lift_posture_settled_step is None:
          self.pre_lift_posture_settled_step = self.step_counter
          self.wide_posture_ready = True
          print(
            "[WIRE] pre-lift posture settled on support; "
            f"holding for {self.pre_lift_posture_hold_time:.2f}s",
            flush=True,
          )
        elif not posture_settled:
          self.pre_lift_posture_settled_step = None
          self.wide_posture_ready = False
      else:
        action = (
          (1.0 - blend) * self.posture_lock_start_action
          + blend * target_action
        )
        action = self._rate_limit_action(
          action, self.last_applied_action, action_rate_limit
        )
    elif self.phase == self.PHASE_ASSIST:
      if self.posture_mode != "assist_policy_blend":
        self.posture_mode = "assist_policy_blend"
        self.posture_lock_active = True
        self.posture_lock_step = self.step_counter
        self.posture_lock_start_action = (
          self.last_applied_action.detach().clone()
          if self.last_applied_action is not None
          else action.detach().clone()
        )
        print(
          "[WIRE] cable length held; standing policy blending in",
          flush=True,
        )
      resume_blend = np.clip(
        (self.step_counter - self.posture_lock_step) * self.dt
        / self.policy_resume_blend_time,
        0.0,
        1.0,
      )
      action = (
        (1.0 - resume_blend) * self.posture_lock_start_action
        + resume_blend * action
      )
      if resume_blend >= 1.0:
        self.posture_lock_active = False
    elif self.phase in (self.PHASE_SETTLE, self.PHASE_RELEASE, self.PHASE_DONE):
      if self.posture_lock_active:
        self.posture_lock_active = False
      if self.phase != self.PHASE_SETTLE:
        self.posture_mode = None
    if (
      waist_control_enabled
      and self.waist_action_indices
      and self.lift_posture_action is not None
    ):
      action = action.clone()
      waist_posture = (
        self.descent_posture_action
        if self.traversal_mode == "descend"
        else self.lift_posture_action
      )
      waist_target = waist_posture.to(
        device=action.device,
        dtype=action.dtype,
      )
      action[:, self.waist_action_indices] = waist_target[
        :, self.waist_action_indices
      ]
    self.last_applied_action = action.detach().clone()
    result = self.env.step(action)

    # ManagerBasedRlEnv performs automatic episode resets inside step().  That
    # bypasses this wrapper's reset(), so mirror the reset for controller state.
    terminated = result[2] if isinstance(result, tuple) and len(result) >= 4 else None
    time_out = result[3] if isinstance(result, tuple) and len(result) >= 4 else None
    if self._has_finished_episode(terminated) or self._has_finished_episode(time_out):
      self._reset_controller_state()
    return result

  def reset(self, **kwargs):
    result = self.env.reset(**kwargs)
    self._reset_controller_state()
    return result

  def __getattr__(self, name):
    return getattr(self.env, name)

@dataclass(frozen=True)
class PlayConfig:
  agent: Literal["zero", "random", "trained"] = "trained"
  traversal_mode: Literal["ascend", "descend"] = "descend"
  checkpoint_file: str | None = None
  motion_file: str | None = None
  num_envs: int | None = None
  device: str | None = None
  video: bool = False
  video_length: int = 200
  video_height: int | None = None
  video_width: int | None = None
  camera: int | str | None = None
  viewer: Literal["auto", "native", "viser"] = "auto"
  no_terminations: bool = False

  _demo_mode: tyro.conf.Suppress[bool] = False

def run_play(task_id: str, cfg: PlayConfig):
  configure_torch_backends()
  device = cfg.device or ("cuda:0" if torch.cuda.is_available() else "cpu")
  env_cfg = load_env_cfg(task_id, play=True)
  agent_cfg = load_rl_cfg(task_id)
  DUMMY_MODE = cfg.agent in {"zero", "random"}
  TRAINED_MODE = not DUMMY_MODE

  if cfg.no_terminations:
    env_cfg.terminations = {}
    print("[INFO]: Terminations disabled")

  is_tracking_task = "motion" in env_cfg.commands and isinstance(env_cfg.commands["motion"], MotionCommandCfg)
  if is_tracking_task and cfg._demo_mode:
    motion_cmd = env_cfg.commands["motion"]
    assert isinstance(motion_cmd, MotionCommandCfg)
    motion_cmd.sampling_mode = "uniform"
  if is_tracking_task:
    motion_cmd = env_cfg.commands["motion"]
    assert isinstance(motion_cmd, MotionCommandCfg)
    if cfg.motion_file is not None and Path(cfg.motion_file).exists():
      motion_cmd.motion_file = cfg.motion_file
    elif DUMMY_MODE:
      if not cfg.registry_name:
        raise ValueError("Tracking tasks require motion file")

  log_dir: Path | None = None
  resume_path: Path | None = None
  if TRAINED_MODE:
    log_root_path = (Path("logs") / "rsl_rl" / agent_cfg.experiment_name).resolve()
    if cfg.checkpoint_file is not None:
      resume_path = Path(cfg.checkpoint_file)
    else:
      resume_path, _ = get_wandb_checkpoint_path(log_root_path, Path(cfg.wandb_run_path))
    log_dir = resume_path.parent

  if cfg.num_envs is not None: env_cfg.scene.num_envs = cfg.num_envs
  if cfg.video_height is not None: env_cfg.viewer.height = cfg.video_height
  if cfg.video_width is not None: env_cfg.viewer.width = cfg.video_width

  # Rule-based playback must be deterministic.  The training environment normally
  # randomizes x/y/yaw at every reset and resamples velocity commands every 3--8 s.
  reset_base = env_cfg.events.get("reset_base")
  if reset_base is not None:
    pose_range = reset_base.params.setdefault("pose_range", {})
    if cfg.traversal_mode == "descend":
      # Existing platform spans x=[2.0, 3.2] with top z=0.6.  Adding z=0.6
      # to the robot's default root pose places both soles on its top surface.
      pose_range.update(
        {
          "x": (2.35, 2.35),
          "y": (0.0, 0.0),
          "z": (0.60, 0.60),
          "roll": (0.0, 0.0),
          "pitch": (0.0, 0.0),
          "yaw": (0.0, 0.0),
        }
      )
    else:
      pose_range.update(
        {
          "x": (0.0, 0.0),
          "y": (0.0, 0.0),
          "z": (0.0, 0.0),
          "roll": (0.0, 0.0),
          "pitch": (0.0, 0.0),
          "yaw": (0.0, 0.0),
        }
      )
    reset_base.params["velocity_range"] = {}
  twist_cfg = env_cfg.commands.get("twist")
  if twist_cfg is not None and hasattr(twist_cfg, "ranges"):
    twist_cfg.resampling_time_range = (1.0e6, 1.0e6)
    twist_cfg.heading_command = False
    twist_cfg.ranges.lin_vel_x = (0.0, 0.0)
    twist_cfg.ranges.lin_vel_y = (0.0, 0.0)
    twist_cfg.ranges.ang_vel_z = (0.0, 0.0)
    twist_cfg.ranges.heading = None

  # Added obstacle geoms can exceed MJWarp's automatically selected broadphase
  # capacity.  The observed minimum was 54, so reserve a comfortable margin.
  env_cfg.sim.nconmax = max(env_cfg.sim.nconmax or 0, 128)

  render_mode = "rgb_array" if (TRAINED_MODE and cfg.video) else None
  env = ManagerBasedRlEnv(cfg=env_cfg, device=device, render_mode=render_mode)

  # =========================================================================
  # Both profiles share the same state machine.  Only edge detection, cable
  # length profile, fixed posture, spawn pose, and anchor placement differ.
  # =========================================================================
  anchor_pos = (
    (3.35, 0.0, 2.4)
    if cfg.traversal_mode == "descend"
    else (2.3, 0.0, 2.4)
  )
  walk_speed = 0.35 if cfg.traversal_mode == "descend" else 0.5
  print(
    f"[WIRE] traversal_mode={cfg.traversal_mode} "
    f"anchor={anchor_pos} walk_speed={walk_speed:.2f}m/s",
    flush=True,
  )
  env = WireAssistWrapper(
    env,
    traversal_mode=cfg.traversal_mode,
    anchor_pos=anchor_pos,
    lin_vel_x=walk_speed,
  )
  
  if TRAINED_MODE and cfg.video:
    env = VideoRecorder(env, video_folder=log_dir / "videos" / "play", step_trigger=lambda step: step == 0, video_length=cfg.video_length, disable_logger=True)

  env = RslRlVecEnvWrapper(env, clip_actions=agent_cfg.clip_actions)
  if DUMMY_MODE:
    action_shape: tuple[int, ...] = env.unwrapped.action_space.shape
    if cfg.agent == "zero":
      class PolicyZero:
        def __call__(self, obs) -> torch.Tensor: return torch.zeros(action_shape, device=env.unwrapped.device)
      policy = PolicyZero()
    else:
      class PolicyRandom:
        def __call__(self, obs) -> torch.Tensor: return 2 * torch.rand(action_shape, device=env.unwrapped.device) - 1
      policy = PolicyRandom()
  else:
    runner_cls = load_runner_cls(task_id) or MjlabOnPolicyRunner
    runner = runner_cls(env, asdict(agent_cfg), device=device)
    runner.load(str(resume_path), load_cfg={"actor": True}, strict=True, map_location=device)
    policy = runner.get_inference_policy(device=device)

  if cfg.viewer == "auto":
    has_display = bool(os.environ.get("DISPLAY") or os.environ.get("WAYLAND_DISPLAY"))
    resolved_viewer = "native" if has_display else "viser"
  else:
    resolved_viewer = cfg.viewer

  if resolved_viewer == "native": NativeMujocoViewer(env, policy).run()
  elif resolved_viewer == "viser": ViserPlayViewer(env, policy).run()
  else: raise RuntimeError(f"Unsupported viewer backend: {resolved_viewer}")
  env.close()

def main():
  import mjlab.tasks  # noqa: F401
  import src.tasks
  all_tasks = list_tasks()
  chosen_task, remaining_args = tyro.cli(tyro.extras.literal_type_from_choices(all_tasks), add_help=False, return_unknown_args=True, config=mjlab.TYRO_FLAGS)
  args = tyro.cli(PlayConfig, args=remaining_args, default=PlayConfig(), prog=sys.argv[0] + f" {chosen_task}", config=mjlab.TYRO_FLAGS)
  run_play(chosen_task, args)

if __name__ == "__main__":
  main()
