"""Script to play RL agent with RSL-RL."""

import os
import sys
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Literal

import torch
import tyro

import mujoco as mj
import numpy as np
from scipy.spatial.transform import Rotation as R

from mjlab.envs import ManagerBasedRlEnv
from mjlab.rl import MjlabOnPolicyRunner, RslRlVecEnvWrapper
from mjlab.tasks.registry import list_tasks, load_env_cfg, load_rl_cfg, load_runner_cls
from mjlab.tasks.tracking.mdp import MotionCommandCfg
from mjlab.utils.os import get_wandb_checkpoint_path
from mjlab.utils.torch import configure_torch_backends
from mjlab.utils.wrappers import VideoRecorder
from mjlab.viewer import NativeMujocoViewer, ViserPlayViewer

class WireAssistWrapper:
  """Obstacle-aware cable tension controller, independent of the walking policy.

  The cable is massless and can only pull toward a fixed world-space anchor.  MuJoCo's
  ``xfrc_applied`` acts at a body's centre of mass, so the moment generated by the
  rear-back attachment point is explicitly added as ``r x F``.
  """

  PHASE_APPROACH, PHASE_LIFT, PHASE_CROSS, PHASE_LOWER, PHASE_DONE = range(5)

  def __init__(
    self,
    env,
    anchor_pos=(2.0, 0.0, 2.5),
    attachment_pos_b=(-0.12, 0.0, 0.18),
    obstacle_body_names=("obstacle_box", "obstacle", "wall_front"),
    lin_vel_x=0.5,
    approach_distance=0.55,
    clearance=0.10,
    lift_kp=420.0,
    lift_kd=90.0,
    pitch_kp=70.0,
    lift_support_ratio=0.95,
    max_tension=420.0,
    tension_rate=900.0,
  ):
    self.env = env
    self.anchor_pos = np.asarray(anchor_pos, dtype=np.float64)
    if self.anchor_pos.shape == (2,):
      self.anchor_pos = np.array([self.anchor_pos[0], 0.0, self.anchor_pos[1]])
    self.attachment_pos_b = np.asarray(attachment_pos_b, dtype=np.float64)
    self.lin_vel_x = lin_vel_x
    self.approach_distance = approach_distance
    self.clearance = clearance
    self.lift_kp, self.lift_kd = lift_kp, lift_kd
    self.pitch_kp = pitch_kp
    self.lift_support_ratio = lift_support_ratio
    self.max_tension, self.tension_rate = max_tension, tension_rate
    self.dt = float(getattr(env.unwrapped, "step_dt", 0.02))

    sim = getattr(env.unwrapped, "sim", None)
    self.mj_model = getattr(env.unwrapped, "model", None)
    self.mj_data = getattr(env.unwrapped, "data", None)
    if self.mj_model is None and sim is not None:
      self.mj_model = getattr(sim, "model", None)
    if self.mj_data is None and sim is not None:
      self.mj_data = getattr(sim, "data", None)
    self.native_model = getattr(self.mj_model, "mj_model", self.mj_model)
    if self.native_model is None or self.mj_data is None:
      raise RuntimeError("WireAssistWrapper could not access the MuJoCo model/data")

    self.body_id = self._find_body(("torso_link", "torso", "pelvis"))
    self.obstacle_body_id = self._find_body(obstacle_body_names)
    if self.body_id < 0:
      raise ValueError("WireAssistWrapper: torso_link/pelvis body was not found")
    self.robot_root_id = int(self.native_model.body_rootid[self.body_id])
    if self.obstacle_body_id < 0:
      raise ValueError(
        f"WireAssistWrapper: obstacle body not found; tried {obstacle_body_names}"
      )
    self.obstacle_geom_id = self._first_box_geom(self.obstacle_body_id)
    if self.obstacle_geom_id < 0:
      raise ValueError("WireAssistWrapper: obstacle body has no box geom")
    self.robot_weight = float(self.native_model.body_subtreemass[self.robot_root_id]) * 9.81

    self.phase = self.PHASE_APPROACH
    self.tension = 0.0
    self.nominal_attachment_z = None
    self.nominal_com_z = None
    self.previous_attachment_z = None
    self.step_counter = 0

  def _find_body(self, names):
    exact = {name.lower() for name in names}
    fallback = -1
    for body_id in range(self.native_model.nbody):
      name = mj.mj_id2name(self.native_model, mj.mjtObj.mjOBJ_BODY, body_id)
      if not name:
        continue
      if name.lower() in exact:
        return body_id
      if fallback < 0 and any(candidate in name.lower() for candidate in exact):
        fallback = body_id
    return fallback

  def _first_box_geom(self, body_id):
    for geom_id in range(self.native_model.ngeom):
      if (
        self.native_model.geom_bodyid[geom_id] == body_id
        and self.native_model.geom_type[geom_id] == mj.mjtGeom.mjGEOM_BOX
      ):
        return geom_id
    return -1

  @staticmethod
  def _numpy(value):
    return value.detach().cpu().numpy() if hasattr(value, "detach") else np.asarray(value)

  def _env0(self, value, item_id):
    array = self._numpy(value)
    return np.array(array[0, item_id] if array.ndim == 3 else array[item_id], copy=True)

  def _set_walking_command(self):
    """Keep the learned locomotion policy on a constant +x body-frame command."""
    command_manager = getattr(self.env.unwrapped, "command_manager", None)
    if command_manager is None:
      return
    try:
      command = command_manager.get_command("twist")
      target = torch.tensor(
        [self.lin_vel_x, 0.0, 0.0], device=command.device, dtype=command.dtype
      )
      with torch.no_grad():
        command[:] = target
    except (KeyError, AttributeError):
      return

  def _obstacle_bounds(self):
    geom_xpos = getattr(self.mj_data, "geom_xpos", None)
    center = (
      self._env0(geom_xpos, self.obstacle_geom_id)
      if geom_xpos is not None
      else self._env0(self.mj_data.xpos, self.obstacle_body_id)
    )
    half_size = np.asarray(self.native_model.geom_size[self.obstacle_geom_id])
    # The research setup assumes an axis-aligned rectangular obstacle in x-z.
    return (
      center[0] - half_size[0],
      center[0] + half_size[0],
      center[2] - half_size[2],
      center[2] + half_size[2],
    )

  def _robot_state(self):
    torso_pos = self._env0(self.mj_data.xpos, self.body_id)
    quat_wxyz = self._env0(self.mj_data.xquat, self.body_id)
    rotation = R.from_quat(
      [quat_wxyz[1], quat_wxyz[2], quat_wxyz[3], quat_wxyz[0]]
    )
    attachment_pos = torso_pos + rotation.apply(self.attachment_pos_b)
    robot_com = self._env0(self.mj_data.subtree_com, self.robot_root_id)
    body_com = self._env0(self.mj_data.xipos, self.body_id)
    pitch = rotation.as_euler("xyz", degrees=False)[1]
    vz = 0.0
    if self.previous_attachment_z is not None:
      vz = (attachment_pos[2] - self.previous_attachment_z) / self.dt
    self.previous_attachment_z = attachment_pos[2]
    return robot_com, body_com, attachment_pos, rotation, pitch, vz

  def _desired_tension(self, robot_com, body_com, attachment_pos, pitch, vz):
    box_front, box_back, box_bottom, box_top = self._obstacle_bounds()
    x = attachment_pos[0]
    if self.nominal_attachment_z is None:
      self.nominal_attachment_z = attachment_pos[2]
    if self.nominal_com_z is None:
      self.nominal_com_z = robot_com[2]
    target_z = self.nominal_attachment_z + (box_top - box_bottom) + self.clearance

    if self.phase == self.PHASE_APPROACH and x >= box_front - self.approach_distance:
      self.phase = self.PHASE_LIFT
    if self.phase == self.PHASE_LIFT and attachment_pos[2] >= target_z:
      self.phase = self.PHASE_CROSS
    if self.phase == self.PHASE_CROSS and x >= box_back + 0.10:
      self.phase = self.PHASE_LOWER
    if self.phase == self.PHASE_LOWER and x >= box_back + 0.55:
      self.phase = self.PHASE_DONE

    if self.phase in (self.PHASE_APPROACH, self.PHASE_DONE):
      return 0.0

    if self.phase == self.PHASE_LIFT:
      vertical_request = self.lift_support_ratio * self.robot_weight
      vertical_request += self.lift_kp * max(0.0, target_z - attachment_pos[2])
      vertical_request -= self.lift_kd * vz
    elif self.phase == self.PHASE_CROSS:
      cross_z = target_z - 0.5 * self.clearance
      vertical_request = 0.75 * self.lift_support_ratio * self.robot_weight
      vertical_request += 0.35 * self.lift_kp * max(0.0, cross_z - attachment_pos[2])
      vertical_request -= 0.5 * self.lift_kd * vz
    else:  # LOWER: retain a little support and then smoothly release it.
      release = np.clip((box_back + 0.55 - x) / 0.45, 0.0, 1.0)
      vertical_request = release * 0.12 * self.max_tension

    vertical_request += self.lift_kp * max(0.0, self.nominal_com_z - robot_com[2])
    cable = self.anchor_pos - attachment_pos
    length = np.linalg.norm(cable)
    if length < 1e-6 or cable[2] <= 1e-3:
      return 0.0
    unit_cable = cable / length
    unit_moment_y = np.cross(attachment_pos - body_com, unit_cable)[1]
    if pitch * unit_moment_y < 0.0:
      vertical_request += self.pitch_kp * abs(pitch)
    return float(np.clip(vertical_request / (cable[2] / length), 0.0, self.max_tension))

  def _apply_cable_force(self, body_com, attachment_pos, desired_tension):
    max_delta = self.tension_rate * self.dt
    self.tension += np.clip(desired_tension - self.tension, -max_delta, max_delta)
    cable = self.anchor_pos - attachment_pos
    cable_length = np.linalg.norm(cable)
    force = np.zeros(3) if cable_length < 1e-6 else self.tension * cable / cable_length
    torque = np.cross(attachment_pos - body_com, force)
    wrench = np.concatenate((force, torque)).astype(np.float32)

    xfrc = self.mj_data.xfrc_applied
    target = xfrc[0, self.body_id] if len(xfrc.shape) == 3 else xfrc[self.body_id]
    if hasattr(target, "copy_"):
      target.copy_(torch.as_tensor(wrench, device=target.device, dtype=target.dtype))
    else:
      target[:] = wrench

  def step(self, action):
    self.step_counter += 1
    self._set_walking_command()
    robot_com, body_com, attachment_pos, _, pitch, vz = self._robot_state()
    desired = self._desired_tension(robot_com, body_com, attachment_pos, pitch, vz)
    self._apply_cable_force(body_com, attachment_pos, desired)
    return self.env.step(action)

  def reset(self, **kwargs):
    result = self.env.reset(**kwargs)
    self.phase = self.PHASE_APPROACH
    self.tension = 0.0
    self.nominal_attachment_z = None
    self.nominal_com_z = None
    self.previous_attachment_z = None
    self.step_counter = 0
    self._set_walking_command()
    return result

  def __getattr__(self, name):
    return getattr(self.env, name)

@dataclass(frozen=True)
class PlayConfig:
  agent: Literal["zero", "random", "trained"] = "trained"
  checkpoint_file: str | None = None
  motion_file: str | None = None
  num_envs: int | None = None
  device: str | None = None
  video: bool = False
  video_length: int = 200
  video_height: int | None = None
  video_width: int | None = None
  camera: int | str | None = None
  viewer: Literal["auto", "native", "viser"] = "auto"
  no_terminations: bool = False

  _demo_mode: tyro.conf.Suppress[bool] = False

def run_play(task_id: str, cfg: PlayConfig):
  configure_torch_backends()
  device = cfg.device or ("cuda:0" if torch.cuda.is_available() else "cpu")
  env_cfg = load_env_cfg(task_id, play=True)
  agent_cfg = load_rl_cfg(task_id)
  DUMMY_MODE = cfg.agent in {"zero", "random"}
  TRAINED_MODE = not DUMMY_MODE

  if cfg.no_terminations:
    env_cfg.terminations = {}
    print("[INFO]: Terminations disabled")

  is_tracking_task = "motion" in env_cfg.commands and isinstance(env_cfg.commands["motion"], MotionCommandCfg)
  if is_tracking_task and cfg._demo_mode:
    motion_cmd = env_cfg.commands["motion"]
    assert isinstance(motion_cmd, MotionCommandCfg)
    motion_cmd.sampling_mode = "uniform"
  if is_tracking_task:
    motion_cmd = env_cfg.commands["motion"]
    assert isinstance(motion_cmd, MotionCommandCfg)
    if cfg.motion_file is not None and Path(cfg.motion_file).exists():
      motion_cmd.motion_file = cfg.motion_file
    elif DUMMY_MODE:
      if not cfg.registry_name:
        raise ValueError("Tracking tasks require motion file")

  log_dir: Path | None = None
  resume_path: Path | None = None
  if TRAINED_MODE:
    log_root_path = (Path("logs") / "rsl_rl" / agent_cfg.experiment_name).resolve()
    if cfg.checkpoint_file is not None:
      resume_path = Path(cfg.checkpoint_file)
    else:
      resume_path, _ = get_wandb_checkpoint_path(log_root_path, Path(cfg.wandb_run_path))
    log_dir = resume_path.parent

  if cfg.num_envs is not None: env_cfg.scene.num_envs = cfg.num_envs
  if cfg.video_height is not None: env_cfg.viewer.height = cfg.video_height
  if cfg.video_width is not None: env_cfg.viewer.width = cfg.video_width

  render_mode = "rgb_array" if (TRAINED_MODE and cfg.video) else None
  env = ManagerBasedRlEnv(cfg=env_cfg, device=device, render_mode=render_mode)

  # =========================================================================
  # 歩行ポリシーは +x へ進み、固定アンカーへの張力だけを独立制御します。
  # =========================================================================
  env = WireAssistWrapper(env, anchor_pos=(2.0, 0.0, 2.5), lin_vel_x=0.5)
  
  if TRAINED_MODE and cfg.video:
    env = VideoRecorder(env, video_folder=log_dir / "videos" / "play", step_trigger=lambda step: step == 0, video_length=cfg.video_length, disable_logger=True)

  env = RslRlVecEnvWrapper(env, clip_actions=agent_cfg.clip_actions)
  if DUMMY_MODE:
    action_shape: tuple[int, ...] = env.unwrapped.action_space.shape
    if cfg.agent == "zero":
      class PolicyZero:
        def __call__(self, obs) -> torch.Tensor: return torch.zeros(action_shape, device=env.unwrapped.device)
      policy = PolicyZero()
    else:
      class PolicyRandom:
        def __call__(self, obs) -> torch.Tensor: return 2 * torch.rand(action_shape, device=env.unwrapped.device) - 1
      policy = PolicyRandom()
  else:
    runner_cls = load_runner_cls(task_id) or MjlabOnPolicyRunner
    runner = runner_cls(env, asdict(agent_cfg), device=device)
    runner.load(str(resume_path), load_cfg={"actor": True}, strict=True, map_location=device)
    policy = runner.get_inference_policy(device=device)

  if cfg.viewer == "auto":
    has_display = bool(os.environ.get("DISPLAY") or os.environ.get("WAYLAND_DISPLAY"))
    resolved_viewer = "native" if has_display else "viser"
  else:
    resolved_viewer = cfg.viewer

  if resolved_viewer == "native": NativeMujocoViewer(env, policy).run()
  elif resolved_viewer == "viser": ViserPlayViewer(env, policy).run()
  else: raise RuntimeError(f"Unsupported viewer backend: {resolved_viewer}")
  env.close()

def main():
  import mjlab.tasks  # noqa: F401
  import src.tasks
  all_tasks = list_tasks()
  chosen_task, remaining_args = tyro.cli(tyro.extras.literal_type_from_choices(all_tasks), add_help=False, return_unknown_args=True, config=mjlab.TYRO_FLAGS)
  args = tyro.cli(PlayConfig, args=remaining_args, default=PlayConfig(), prog=sys.argv[0] + f" {chosen_task}", config=mjlab.TYRO_FLAGS)
  run_play(chosen_task, args)

if __name__ == "__main__":
  main()
